### ISSUE TITLE
ReferenceError: structuredClone is not defined

### ISSUE THREAD

**Issue by SkullCandby** [rckprtr/pumpdotfun-sdk#20]
I keep gettinng this error

ReferenceError: structuredClone is not defined
    at convertIdlToCamelCase (C:\Users\gdmes\pumpdotfun-sdk\node_modules\@coral-xyz\anchor\src\idl.ts:337:25)
    at new Program (C:\Users\gdmes\pumpdotfun-sdk\node_modules\@coral-xyz\anchor\src\program\index.ts:289:48)
    at new PumpFunSDK (C:\Users\gdmes\pumpdotfun-sdk\src\pumpfun.ts:58:20)
    at main (C:\Users\gdmes\pumpdotfun-sdk\example\basic\index.ts:51:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by rckprtr** [comment]
What version of node are you using?

`node -v`

Im on version:
`v20.10.0`

**Comment by SkullCandby** [comment]
I was using older node version, so this is was the problem
